version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=ahaap
      - POSTGRES_PASSWORD=1245
      - POSTGRES_DB=bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://ahaap:1245@postgres:5432/bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]